# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'

target 'JAQDiceView' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JAQDiceView
  pod 'JAQDiceView'
  pod ‘Firebase/Core’
  pod ‘Firebase/AdMob’

end
